### ISSUE TITLE
Error Node expected version

### ISSUE THREAD

**Issue by DR-RepDir** [render-examples/strapi-sqlite#6]
Jan 25 06:00:52 PM  ==> Checking out commit 6583634b40518cc085a7192013f2086e3f5e001d in branch master
Jan 25 06:00:52 PM  ==> Downloading cache...
Jan 25 06:00:55 PM  ==> Detected Node version 15.6.0
Jan 25 06:00:56 PM  ==> Detected Node version 15.6.0
Jan 25 06:00:57 PM  ==> Installing dependencies with Yarn...
Jan 25 06:00:57 PM  yarn install v1.22.10
Jan 25 06:00:57 PM  [1/5] Validating package.json...
Jan 25 06:00:57 PM  [2/5] Resolving packages...
Jan 25 06:00:58 PM  [3/5] Fetching packages...
Jan 25 06:01:11 PM  warning url-loader@1.1.2: Invalid bin field for "url-loader".
Jan 25 06:01:28 PM  error strapi@3.4.1: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "15.6.0"
Jan 25 06:01:28 PM  error Found incompatible module.
Jan 25 06:01:28 PM  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by wendorf** [comment]
Hi @dr-zappik ,

I see that your service is using Node 15.6.0. However, the [strapi](https://www.npmjs.com/package/strapi) package only does not have support for node 15.6.0. According to their [Recommended requirements](https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#recommended-requirements) doc:

> Node LTS (v12 or V14) Note that odd-number releases of Node will never be supported (e.g. v13, v15).

Please see our [Specifying a Node Version](https://render.com/docs/node-version) doc if you need assistance changing the version of Node for your service.
